version: '3.4'

networks:
  default:
    driver: bridge
  traefik:
    internal: true

services:
  traefik:
    image: traefik:${VERSION}
    labels:     
      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https

      # middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    networks:
      - default
      - traefik
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./config/acme.json:/acme.json
      - ./config/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro