version: '3'

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:ect/traefic/traefik.toml
      - ./config/acme.json:/acme.json
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-512m}

networks:
  web:
    external: true
