version: '3.4'
  
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - ${NETWORK_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml
      - ./config/acme.json:/acme.json
    container_name: traefik
    logging:
      options:
        max-size: ${LOG_MAX_SIZE:-512m}

networks:
  web:
    external: true
    name: ${NETWORK_NAME} 